services:

  # web-api:
  #   container_name: call-qa-web-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - "8000:8000"
  #     - 5678:5678
  #   command: |
  #     bash -c "
  #     python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
  #   volumes:
  #     - ./app:/app
  #   networks:
  #     - call-qa-net

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.6
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'


  neo4j:
    image: neo4j:5.19
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: 'neo4j/testtest'
      NEO4J_dbms_connector_bolt_listen__address: ':7687'
      NEO4J_dbms_connector_bolt_advertised__address: 'localhost:7687'

volumes:
  weaviate_data:

networks:
  call-qa-net:
    driver: bridge
