# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import template_service_pb2 as template__service__pb2

GRPC_GENERATED_VERSION = "1.73.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in template_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TemplateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTemplate = channel.unary_unary(
            "/narrator.templates.TemplateService/GetTemplate",
            request_serializer=template__service__pb2.GetTemplateRequest.SerializeToString,
            response_deserializer=common__pb2.Template.FromString,
            _registered_method=True,
        )
        self.FindTemplates = channel.unary_unary(
            "/narrator.templates.TemplateService/FindTemplates",
            request_serializer=template__service__pb2.FindTemplatesRequest.SerializeToString,
            response_deserializer=template__service__pb2.FindTemplatesResponse.FromString,
            _registered_method=True,
        )
        self.UpsertTemplate = channel.unary_unary(
            "/narrator.templates.TemplateService/UpsertTemplate",
            request_serializer=template__service__pb2.UpsertTemplateRequest.SerializeToString,
            response_deserializer=common__pb2.Template.FromString,
            _registered_method=True,
        )


class TemplateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FindTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpsertTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TemplateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetTemplate": grpc.unary_unary_rpc_method_handler(
            servicer.GetTemplate,
            request_deserializer=template__service__pb2.GetTemplateRequest.FromString,
            response_serializer=common__pb2.Template.SerializeToString,
        ),
        "FindTemplates": grpc.unary_unary_rpc_method_handler(
            servicer.FindTemplates,
            request_deserializer=template__service__pb2.FindTemplatesRequest.FromString,
            response_serializer=template__service__pb2.FindTemplatesResponse.SerializeToString,
        ),
        "UpsertTemplate": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertTemplate,
            request_deserializer=template__service__pb2.UpsertTemplateRequest.FromString,
            response_serializer=common__pb2.Template.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "narrator.templates.TemplateService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "narrator.templates.TemplateService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class TemplateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTemplate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/narrator.templates.TemplateService/GetTemplate",
            template__service__pb2.GetTemplateRequest.SerializeToString,
            common__pb2.Template.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FindTemplates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/narrator.templates.TemplateService/FindTemplates",
            template__service__pb2.FindTemplatesRequest.SerializeToString,
            template__service__pb2.FindTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpsertTemplate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/narrator.templates.TemplateService/UpsertTemplate",
            template__service__pb2.UpsertTemplateRequest.SerializeToString,
            common__pb2.Template.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
