# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: template_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 0, "", "template_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16template_service.proto\x12\x12narrator.templates\x1a\x0c\x63ommon.proto")\n\x12GetTemplateRequest\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t"F\n\x14\x46indTemplatesRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\r"E\n\x15\x46indTemplatesResponse\x12,\n\ttemplates\x18\x01 \x03(\x0b\x32\x19.narrator.common.Template"D\n\x15UpsertTemplateRequest\x12+\n\x08template\x18\x01 \x01(\x0b\x32\x19.narrator.common.Template2\xa1\x02\n\x0fTemplateService\x12P\n\x0bGetTemplate\x12&.narrator.templates.GetTemplateRequest\x1a\x19.narrator.common.Template\x12\x64\n\rFindTemplates\x12(.narrator.templates.FindTemplatesRequest\x1a).narrator.templates.FindTemplatesResponse\x12V\n\x0eUpsertTemplate\x12).narrator.templates.UpsertTemplateRequest\x1a\x19.narrator.common.Templateb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "template_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETTEMPLATEREQUEST"]._serialized_start = 60
    _globals["_GETTEMPLATEREQUEST"]._serialized_end = 101
    _globals["_FINDTEMPLATESREQUEST"]._serialized_start = 103
    _globals["_FINDTEMPLATESREQUEST"]._serialized_end = 173
    _globals["_FINDTEMPLATESRESPONSE"]._serialized_start = 175
    _globals["_FINDTEMPLATESRESPONSE"]._serialized_end = 244
    _globals["_UPSERTTEMPLATEREQUEST"]._serialized_start = 246
    _globals["_UPSERTTEMPLATEREQUEST"]._serialized_end = 314
    _globals["_TEMPLATESERVICE"]._serialized_start = 317
    _globals["_TEMPLATESERVICE"]._serialized_end = 606
# @@protoc_insertion_point(module_scope)
