name: Build Contracts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - run: buf lint
      - run: buf breaking --against .git#branch=main
      - run: buf generate
      - run: pip install build
      - run: python -m build -w
      - run: twine upload dist/* --repository pypi -u __token__ -p ${{ secrets.PYPI_TOKEN }}
