base_templates = [
    {
        "name": "trait_attribution_v1",
        "version": "1.0.2",
        "title": "Trait attribution",
        "description": "Character reveals or gains a personal trait.",
        "keywords": [
            "character shows bravery",
            "demonstrates courage",
            "exhibits kindness",
            "reveals true nature",
            "trait becomes evident",
            "personal quality",
            "inner strength",
            "hidden trait emerges",
            "moral weakness",
            "displays cruelty",
            "character described as cunning",
            "emotional shift",
            "quality attribution",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "description": "Character name",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "trait": {
                "name": "trait",
                "type": "STRING",
                "description": "Trait or quality name",
            },
            "chapter": {
                "name": "chapter",
                "type": "INT",
                "description": "Chapter number",
            },
            "summary": {
                "name": "summary",
                "type": "STRING",
                "required": False,
                "description": "Brief explanation",
            },
        },
        "extract_cypher": "trait_attribution_v1.j2",
        "augment_cypher": "trait_attribution_aug_v1.j2",
        "graph_relation": {
            "predicate": "HAS_TRAIT",
            "subject": "$character",
            "value": "$trait",
            "object": "$trait",
        },
        "return_map": {"c": "Character", "t": "Trait"},
    },
    {
        "name": "membership_change_v1",
        "version": "1.0.2",
        "title": "Membership change",
        "description": "Character joins, leaves or betrays a group.",
        "keywords": [
            "joins a faction",
            "leaves the group",
            "betrays allies",
            "switches allegiance",
            "defects from faction",
            "expelled from guild",
            "abandon cause",
            "loyalty shift",
            "membership ends",
            "infiltrates enemy",
            "joins rival group",
            "breaks with order",
            "becomes outsider",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "description": "Character name",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "faction": {
                "name": "faction",
                "type": "STRING",
                "description": "Faction name",
                "is_entity_ref": True,
                "entity_type": "FACTION",
            },
            "chapter": {
                "name": "chapter",
                "type": "INT",
                "description": "Chapter number",
            },
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "membership_change_v1.j2",
        "augment_cypher": "membership_change_aug_v1.j2",
        "graph_relation": {
            "predicate": "MEMBER_OF",
            "subject": "$character",
            "value": "$faction",
            "object": "$faction",
        },
        "return_map": {"a": "Character", "b": "Faction"},
    },
    {
        "name": "character_relation_v1",
        "version": "1.0.2",
        "title": "Character relation",
        "description": "Two characters form or change a relationship.",
        "keywords": [
            "become allies",
            "turn into enemies",
            "reveal sibling connection",
            "mentor takes apprentice",
            "relationship evolves",
            "friends to rivals",
            "discover they are family",
            "form alliance",
            "conflict between characters",
            "develop friendship",
            "reconcile after betrayal",
            "change in relation",
            "new rivalry",
        ],
        "category": "EventInsert",
        "slots": {
            "character_a": {
                "name": "character_a",
                "type": "STRING",
                "description": "First character",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "character_b": {
                "name": "character_b",
                "type": "STRING",
                "description": "Second character",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "relation_type": {
                "name": "relation_type",
                "type": "STRING",
                "description": "Relation type: ALLY, RIVAL, SIBLING, PARENT",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "character_relation_v1.j2",
        "augment_cypher": "character_relation_aug_v1.j2",
        "graph_relation": {
            "predicate": "RELATION_WITH",
            "subject": "$character_a",
            "value": "$relation_type",
            "object": "$character_b",
        },
        "return_map": {"a": "Character", "b": "Character"},
    },
    {
        "name": "ownership_v1",
        "version": "1.0.2",
        "title": "Item ownership",
        "description": "Character gains or holds an item.",
        "keywords": [
            "acquires artifact",
            "receives magical item",
            "inherits heirloom",
            "gift from ally",
            "steals valuable object",
            "buys quest tool",
            "finds ancient weapon",
            "gains possession",
            "holds relic",
            "claims treasure",
            "takes item",
            "owns special item",
            "equips item",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "item": {
                "name": "item",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "ITEM",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "ownership_v1.j2",
        "augment_cypher": "ownership_aug_v1.j2",
        "graph_relation": {
            "predicate": "OWNS_ITEM",
            "subject": "$character",
            "value": "$item",
            "object": "$item",
        },
        "return_map": {"c": "Character", "i": "Item"},
    },
    {
        "name": "relocation_v1",
        "version": "1.0.2",
        "title": "Relocation / arrives at place",
        "description": "Character arrives at or leaves a place.",
        "keywords": [
            "arrives in city",
            "leaves home",
            "escapes prison",
            "enters new territory",
            "travels to village",
            "flees homeland",
            "reaches destination",
            "discovers location",
            "returns home",
            "settles in place",
            "crosses border",
            "moves between places",
            "arrives at stronghold",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "place": {"name": "place", "type": "STRING", "is_entity_ref": True},
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "relocation_v1.j2",
        "augment_cypher": "relocation_aug_v1.j2",
        "graph_relation": {
            "predicate": "AT_LOCATION",
            "subject": "$character",
            "value": "$place",
            "object": "$place",
        },
        "return_map": {"c": "Character", "p": "Place"},
    },
    {
        "name": "emotion_state_v1",
        "version": "1.0.2",
        "title": "Emotional state toward target",
        "description": "Character feels an emotion toward someone or in general.",
        "keywords": [
            "feels love for someone",
            "experiences hatred",
            "overwhelmed with grief",
            "envies rival",
            "emotional reaction",
            "struggles with jealousy",
            "deep sadness",
            "resentment builds",
            "develops affection",
            "rage intensifies",
            "feels fear",
            "compassion toward other",
            "emotional bond",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "description": "Name of the character",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "emotion": {
                "name": "emotion",
                "type": "STRING",
                "description": "Emotion name, e.g., HATE, LOVE",
            },
            "target": {
                "name": "target",
                "type": "STRING",
                "description": "Target of the emotion",
                "required": False,
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "chapter": {
                "name": "chapter",
                "type": "INT",
                "description": "Chapter number",
            },
            "summary": {
                "name": "summary",
                "type": "STRING",
                "description": "Narrative summary",
                "required": False,
            },
        },
        "extract_cypher": "emotion_state_v1.j2",
        "augment_cypher": "emotion_state_aug_v1.j2",
        "graph_relation": {
            "predicate": "FEELS",
            "subject": "$character",
            "value": "$emotion",
            "object": "$target",
        },
        "return_map": {"c": "Character", "t": "Character"},
    },
    {
        "name": "vow_promise_v1",
        "version": "1.0.2",
        "title": "Vow or promise",
        "description": "Character makes a vow or promise toward a goal.",
        "keywords": [
            "swears revenge",
            "pledges loyalty",
            "promises protection",
            "makes a vow",
            "commits to a cause",
            "declares intent",
            "takes an oath",
            "binds self to goal",
            "vows to act",
            "makes solemn promise",
            "personal commitment",
            "oath of allegiance",
            "sets goal with intent",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "goal": {
                "name": "goal",
                "type": "STRING",
                "description": "Promise essence / goal",
                "is_entity_ref": True,
                "entity_type": "GOAL",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "vow_promise_v1.j2",
        "augment_cypher": "vow_promise_aug_v1.j2",
        "graph_relation": {
            "predicate": "VOWS",
            "subject": "$character",
            "value": "$goal",
            "object": "$goal",
        },
        "return_map": {"c": "Character", "g": "Goal"},
    },
    {
        "name": "death_event_v1",
        "version": "1.0.2",
        "title": "Death of character",
        "description": "Character dies or is believed to have died.",
        "keywords": [
            "killed in battle",
            "dies suddenly",
            "sacrifices life",
            "murdered by assassin",
            "believed dead",
            "tragic death",
            "confirmed death",
            "death scene",
            "false death",
            "character is killed",
            "dies for cause",
            "natural death",
            "life ends",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "death_event_v1.j2",
        "augment_cypher": "death_event_aug_v1.j2",
        "graph_relation": {
            "predicate": "IS_ALIVE",
            "subject": "$character",
            "value": "false",
        },
        "return_map": {"c": "Character"},
    },
    {
        "name": "belief_ideology_v1",
        "version": "1.0.2",
        "title": "Belief or ideology",
        "description": "Character adopts, rejects or declares a belief or ideology.",
        "keywords": [
            "converts to new faith",
            "abandons old beliefs",
            "questions ideology",
            "embraces religion",
            "declares belief",
            "finds spiritual path",
            "swears by doctrine",
            "rejects philosophy",
            "turns to religion",
            "renounces former views",
            "belief transformation",
            "internal struggle with belief",
            "commitment to ideology",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {"name": "character", "type": "STRING", "is_entity_ref": True},
            "ideology": {
                "name": "ideology",
                "type": "STRING",
                "description": "Name of ideology, deity or belief",
                "is_entity_ref": True,
                "entity_type": "IDEOLOGY",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "belief_ideology_v1.j2",
        "augment_cypher": "belief_ideology_aug_v1.j2",
        "graph_relation": {
            "predicate": "BELIEVES_IN",
            "subject": "$character",
            "value": "$ideology",
            "object": "$ideology",
        },
        "return_map": {"c": "Character", "d": "Ideology"},
    },
    {
        "name": "title_acquisition_v1",
        "version": "1.0.2",
        "title": "Title acquisition",
        "description": "Character is granted or assumes a new title or role.",
        "keywords": [
            "receives noble title",
            "promoted to general",
            "becomes master",
            "appointed leader",
            "gains authority",
            "ascends to nobility",
            "granted new rank",
            "takes official role",
            "title acquisition",
            "position of power",
            "formal promotion",
            "acknowledged status",
            "inherits role",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "title_name": {
                "name": "title_name",
                "type": "STRING",
                "description": "Title/role name",
                "is_entity_ref": True,
                "entity_type": "TITLE",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "title_acquisition_v1.j2",
        "augment_cypher": "title_acquisition_aug_v1.j2",
        "graph_relation": {
            "predicate": "HAS_TITLE",
            "subject": "$character",
            "value": "$title_name",
            "object": "$title_name",
        },
        "return_map": {"c": "Character", "t": "Title"},
    },
    {
        "name": "identity_change_v1",
        "version": "1.0.0",
        "title": "Identity change / reincarnation",
        "description": "Character assumes a new identity replacing a former one.",
        "keywords": [
            "reincarnation",
            "new identity",
            "assumes name",
            "alias revealed",
            "reborn as",
            "identity shift",
            "takes new body",
            "former self",
            "changes persona",
            "secret identity",
            "becomes someone else",
            "past life uncovered",
            "alias established",
        ],
        "category": "EventInsert",
        "slots": {
            "character_new": {
                "name": "character_new",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "character_old": {
                "name": "character_old",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "identity_change_v1.j2",
        "augment_cypher": "identity_change_aug_v1.j2",
        "graph_relation": {
            "predicate": "FORMER_IDENTITY",
            "subject": "$character_new",
            "value": "$character_old",
        },
        "return_map": {"a": "Character"},
    },
    {
        "name": "item_creation_v1",
        "version": "1.0.0",
        "title": "Item creation or invention",
        "description": "Character creates or invents a new item.",
        "keywords": [
            "creates artifact",
            "builds device",
            "invents tool",
            "crafts weapon",
            "forges item",
            "constructs portal",
            "develops tech",
            "makes gadget",
            "brews potion",
            "engineers machine",
            "fabricates object",
            "item creation",
            "prototype built",
        ],
        "category": "EventInsert",
        "slots": {
            "character": {
                "name": "character",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "item_creation_v1.j2",
        "augment_cypher": "item_creation_aug_v1.j2",
        "graph_relation": {
            "predicate": "HAS_CREATED_ITEM",
            "subject": "$character",
            "value": "true",
        },
        "return_map": {"c": "Character"},
    },
    {
        "name": "conflict_event_v1",
        "version": "1.0.0",
        "title": "Conflict / attack",
        "description": "One character or group attacks another.",
        "keywords": [
            "attacks",
            "assault",
            "battle",
            "skirmish",
            "raids",
            "ambush",
            "siege",
            "clash with",
            "engages enemy",
            "storms location",
            "conflict breaks out",
            "fights against",
            "violent encounter",
        ],
        "category": "EventInsert",
        "slots": {
            "attacker": {
                "name": "attacker",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "CHARACTER",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "conflict_event_v1.j2",
        "augment_cypher": "conflict_event_aug_v1.j2",
        "graph_relation": {
            "predicate": "HAS_ATTACKED",
            "subject": "$attacker",
            "value": "true",
        },
        "return_map": {"a": "Character"},
    },
    {
        "name": "destruction_event_v1",
        "version": "1.0.0",
        "title": "Destruction of place or item",
        "description": "An object or location is destroyed or rendered unusable.",
        "keywords": [
            "destroyed",
            "demolished",
            "explodes",
            "ruined",
            "shattered",
            "burned down",
            "levelled",
            "obliterated",
            "wrecked",
            "self-destruct",
            "facility destroyed",
            "structure collapse",
            "object annihilated",
        ],
        "category": "EventInsert",
        "slots": {
            "target": {
                "name": "target",
                "type": "STRING",
                "is_entity_ref": True,
                "entity_type": "ITEM_OR_PLACE",
            },
            "chapter": {"name": "chapter", "type": "INT"},
            "summary": {"name": "summary", "type": "STRING", "required": False},
        },
        "extract_cypher": "destruction_event_v1.j2",
        "augment_cypher": "destruction_event_aug_v1.j2",
        "graph_relation": {
            "predicate": "IS_INTACT",
            "subject": "$target",
            "value": "false",
        },
        "return_map": {"t": "Target"},
    },
]
